name: "Rollback Action"
description: "Rollback to previous version"

runs:
  using: "composite"
  steps:
    - name: Rollback Deployment
      run: |
        VERSION=$(cat .rollback_tag)
        echo "Rolling back $VERSION environment to the previous version"
        # Example rollback logic:
        echo "Stopping current containers..."
        echo "Deploying previous stable version from registry..."
      shell: bash
