name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sample-react-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ env.IMAGE_NAME }}

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploying Application to Dev
        run: echo "Deploying application to Dev..."

  approval-dev:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://your-dev-environment-url.example.com
    steps:
      - name: Waiting for manual approval for Dev
        run: echo "Awaiting manual approval for Dev"

  rollback-dev:
    needs: approval-dev
    if: failure() || cancelled() # Rollback on rejection or cancellation
    runs-on: ubuntu-latest
    steps:
      - name: Rollback Dev deployment
        run: |
          echo "Rolling back Dev deployment..."
