name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sample-react-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ env.IMAGE_NAME }}

  deploy-dev:
    needs: build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Deploying Application to Dev
        run: echo "Deploying application to Dev..."

  approval-dev:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Prompt for Dev Approval (Yes/No)
        uses: actions/github-script@v7
        with:
          script: |
            const approval = '${{ github.event.inputs.approval || "no" }}';
            if (approval !== 'yes') {
              core.setFailed('Approval not granted. Initiating rollback.');
            }

      - name: Rollback Dev if Not Approved
        if: failure()
        run: |
          echo "Rolling back Dev deployment..."
          # Add rollback commands here
