name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sample-react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Building Image
        run: echo "Building Image"

  dev-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Application to Dev
        run: echo "Deploying application to Dev..."

  uat-approval:
    needs: [build, dev-deploy]
    runs-on: ubuntu-latest
    environment:
      name: uat
    steps:
      - name: Waiting for manual approval for UAT
        run: echo "Awaiting manual approval for UAT"

  uat-deploy:
    needs: uat-approval
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Application to UAT
        run: echo "Deploying application to UAT..."

  uat-rollback:
    needs: uat-deploy
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Rollback UAT Deployment
        run: |
          VERSION=$(cat .rollback_tag)
          echo "Rolling back UAT environment to version $VERSION"

  prod-approval:
    needs: [uat-deploy]
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Waiting for manual approval for Prod
        run: echo "Awaiting manual approval for Prod"

  prod-deploy:
    needs: prod-approval
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Application to Prod
        run: echo "Deploying application to Production..."

  prod-rollback:
    needs: prod-deploy
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Rollback Prod Deployment
        run: |
          VERSION=$(cat .rollback_tag)
          echo "Rolling back Production environment to version $VERSION"

  manual-rollback:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Manual Rollback
        run: |
          VERSION=$(cat .rollback_tag)
          echo "Manually rolling back to version $VERSION"
