name: Build and Promote with Conditional Rejection Handling

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      rollback_version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Rollback Version
        id: get_version
        run: |
          VERSION=$(cat .rollback_tag)
          echo "Rollback version is $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Build Application
        run: echo "Building application..."

  dev-deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Deploy to dev
        run: echo "Deploying to dev..."

  dev-approval:
    needs: dev-deploy
    runs-on: ubuntu-latest
    environment:
      name: is-dev-build-success
    steps:
      - name: Build Approval Check
        run: echo "Waiting for dev build approval..."

  dev-build-rejected:
    needs: [build, dev-approval]
    if: failure() # Runs if build approval is rejected
    runs-on: ubuntu-latest
    steps:
      - name: Handle Build Rejection
        run: |
          echo "Dev approval rejected. Executing alternative actions..."
          VERSION=${{ needs.build.outputs.rollback_version }}
          echo "Deploying back $VERSION"

  uat-promote-approval:
    needs: [dev-approval]
    if: success() # Only runs if build approval is successful
    runs-on: ubuntu-latest
    environment:
      name: promote-to-uat
    steps:
      - name: Promotion Approval Check
        run: echo "Waiting for UAT approval..."

  uat-deploy:
    needs: [uat-promote-approval]
    if: success()
    runs-on: ubuntu-latest
    environment:
      name: uat
    steps:
      - name: Deploying to UAT Environment
        run: echo "Deploying the approved build to the UAT environment..."

  uat-approval:
    needs: uat-deploy
    runs-on: ubuntu-latest
    environment:
      name: is-uat-build-success
    steps:
      - name: Build Approval Check
        run: echo "Waiting for build approval..."

  uat-build-rejected:
    needs: [build, uat-approval]
    if: failure() # Runs if build approval is rejected
    runs-on: ubuntu-latest
    steps:
      - name: Handle Build Rejection
        run: |
          echo "Build approval rejected. Executing alternative actions..."
          VERSION=${{ needs.build.outputs.rollback_version }}
          echo "Deploying back $VERSION"

  prod-promote-approval:
    needs: [uat-approval]
    if: success() # Only runs if build approval is successful
    runs-on: ubuntu-latest
    environment:
      name: promote-to-prod
    steps:
      - name: Promotion Approval Check
        run: echo "Waiting for Prod approval..."

  prod-deploy:
    needs: [prod-promote-approval]
    if: success()
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Deploying to UAT Environment
        run: echo "Deploying the approved build to the UAT environment..."

  prod-approval:
    needs: prod-deploy
    runs-on: ubuntu-latest
    environment:
      name: is-prod-build-success
    steps:
      - name: Build Approval Check
        run: echo "Waiting for build approval..."

  prod-build-rejected:
    needs: [build, prod-approval]
    if: failure() # Runs if build approval is rejected
    runs-on: ubuntu-latest
    steps:
      - name: Handle Build Rejection
        run: |
          echo "Build approval rejected. Executing alternative actions..."
          VERSION=${{ needs.build.outputs.rollback_version }}
          echo "Deploying back $VERSION"

  deployment-complete:
    needs: [prod-approval]
    runs-on: ubunut-latest
    steps:
      - name: Deployment Complete
        run: echo "Deployment is completed"
