name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: sample-react-app
    steps:
      - name: Building Image
        run: echo "Building Image"

  dev-deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Application to Dev
        run: echo "Deploying application to Dev..."

  dev-approval:
    needs: dev-deploy
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      - name: Waiting for manual approval for Dev
        run: echo "Awaiting manual approval for Dev"

  dev-rollback:
    needs: dev-approval
    if: failure() || cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: Rollback Dev deployment
        run: |
          echo "Rolling back Dev deployment..."

  uat-promotional-approval:
    needs: dev-approval
    runs-on: ubuntu-latest
    environment:
      name: uat
    steps:
      - name: Waiting for manual approval for Uat
        run: echo "Awaiting manual approval for Uat"

  end-at-dev:
    needs: uat-promotional-approval
    if: failure() || cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: End Pipeline
        run: |
          echo "Ending Pipeline at Dev..."

  uat-deploy:
    needs: uat-promotional-approval
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Application to UAT
        run: echo "Deploying application to UAT..."

  uat-approval:
    needs: uat-deploy
    runs-on: ubuntu-latest
    environment:
      name: uat
    steps:
      - name: Waiting for manual approval for Uat
        run: echo "Awaiting manual approval for Uat"

  uat-rollback:
    needs: uat-approval
    if: failure() || cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: Rollback Uat deployment
        run: |
          echo "Rolling back Uat deployment..."

  prod-promotional-approval:
    needs: uat-approval
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Waiting for manual approval for Prod
        run: echo "Awaiting manual approval for Prod"

  end-at-uat:
    needs: prod-promotional-approval
    if: failure() || cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: End Pipeline
        run: |
          echo "Ending Pipeline at Uat..."

  prod-deploy:
    needs: prod-promotional-approval
    runs-on: ubuntu-latest
    steps:
      - name: Deploying Application to Prod
        run: echo "Deploying application to Production..."

  prod-approval:
    needs: prod-deploy
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Waiting for manual approval for Production
        run: echo "Awaiting manual approval for Production"

  prod-rollback:
    needs: prod-approval
    if: failure() || cancelled()
    runs-on: ubuntu-latest
    steps:
      - name: Rollback Prod deployment
        run: |
          echo "Rolling back Prod deployment..."

  deployment-completed:
    needs: prod-approval
    runs-on: ubuntu-latest
    steps:
      - name: Deployment Success
        run: |
          echo "Deployyment completed..."
